### ISSUE TITLE
This seems to be unusable

### ISSUE THREAD

**Issue by aadd445aadda** [jasonthewhale/space_id_web3py#1]
I purchased a bnb domain name, but the function name I called is different from the one on the official website, and it has no effect after I ran it

**Comment by jasonthewhale** [comment]
This script is for limited launch in last year, and probably not work for current contract.
If you need I can rewrite this repository.

**Comment by aadd445aadda** [comment]
No need, I have already solved this problem. Thank you very much, the source code is great!
